<!-- 1. Datos personales dtd01.xml -->
<?xml version="1.0" encoding="UTF-8"?> 
<!DOCTYPE persona [
    <!ELEMENT persona EMPTY>
    <!ATTLIST persona nombre CDATA #IMPLIED> 
]>

<persona nombre="03141592E" />

<!-- ############################################################ -->

<!-- 2. Película dtd02.xml -->
<?xml version="1.0" encoding="UTF-8"?> 
<!DOCTYPE pelicula [
    <!ELEMENT pelicula EMPTY>
    <!ATTLIST pelicula titulo CDATA #IMPLIED> 
]>

<pelicula titulo="La diligencia"/>

<!-- ############################################################ -->

<!-- 3. Cuadros dtd03.xml -->
<?xml version="1.0" encoding="UTF-8"?> 
<!DOCTYPE cuadros [
    <!ELEMENT cuadros (cuadro*)>
    <!ELEMENT cuadro EMPTY>
    <!ATTLIST cuadro titulo ID #REQUIRED> 
    <!ATTLIST cuadro autor CDATA #REQUIRED>
]>

<cuadros>
    <cuadro titulo="Adán_y_Eva" autor="Alberto Durero" /> 
    <cuadro  titulo="Adán_y_Eva_2" autor="Lucas Cranach, el viejo"/>
</cuadros>

<!-- ############################################################ -->

<!-- 4. Lista de la compra dtd04.xml -->
<?xml version="1.0" encoding="UTF-8"?> 
<!DOCTYPE listaCompra [
    <!ELEMENT listaCompra (item*)> 
    <!ELEMENT item EMPTY>
    <!ATTLIST item nombre CDATA #REQUIRED> 
    <!ATTLIST item cantidad CDATA #REQUIRED>
]>

<listaCompra>
    <item nombre="leche" cantidad="12 litros"></item> 
    <item nombre="pan" cantidad="3 barras de cuarto" />
</listaCompra>

<!-- ############################################################ -->

<!-- 5. Jugadores de fútbol dtd05.xml -->
<?xml version="1.0" encoding="UTF-8"?> 
<!DOCTYPE futbol [
    <!ELEMENT futbol (jugador*)>
    <!ELEMENT jugador EMPTY>
    <!ATTLIST jugador nombre NMTOKENS #REQUIRED> 
    <!ATTLIST jugador codigo ID #REQUIRED>
]>

<futbol>
    <jugador nombre="Alfredo Di Stéfano" codigo="C1"/> 
    <jugador nombre="Edison Arantes do Nascimento, Pelé" codigo="C2" />
    <jugador nombre="Diego Armando Maradona" codigo="C3" /> 
    <jugador nombre="Johan Cruyff" codigo="C4" />
</futbol>

<!-- ############################################################ -->

<!-- 6. Jugadores y equipos de fútbol dtd06.xml -->
<?xml version="1.0" encoding="UTF-8"?> 
<!DOCTYPE futbol [
    <!ELEMENT futbol ((jugador|equipo)*)> 
    <!ELEMENT jugador EMPTY>
    <!ATTLIST jugador nombre NMTOKENS #REQUIRED> 
    <!ATTLIST jugador codigo ID #REQUIRED> 
    <!ELEMENT equipo EMPTY>
    <!ATTLIST equipo nombre CDATA #REQUIRED>
    <!ATTLIST equipo jugadores IDREFS #IMPLIED> 
]>

<futbol>
    <jugador nombre="Alfredo Di Stéfano" codigo="ads"/> 
    <jugador nombre="Edison Arantes do Nascimento" codigo="ean"/>
    <jugador nombre="Diego Armando Maradona" codigo="dam" />
    <jugador nombre="Johan Cruyff" codigo="jc" />
    <equipo nombre="Società Sportiva Calcio Napoli" jugadores="dam"  />
</futbol>
